### PR TITLE
Fix cors

### PR DESCRIPTION
**Pull request by troeger**
An attempt to fix the CORS issues. You need to set KUBEPORTAL_ALLOWED_URLS with the list of URLs this server is reachable under.  It would be nice to have a test against the latest kubeportal-Frontensegeln Code.

### CODE REVIEW

**Review by kat-hi — CHANGES_REQUESTED** [review]
does not work, I'll send you screenshots in ris.chat.

**Review by kat-hi — APPROVED** [review]
good job.

**Comment by kat-hi** [comment]
and we should decide whether we solve the cookie-is-not-visible issue or you just add a token to the login-response payload

**Comment by troeger** [comment]
We decided to make the JWT token an explicit part of the login response.

**Comment by kat-hi** [comment]
these changes don't include our decision to provide a JWT token

**Pull request merged**
